/*
 * Copyright 2011 Free Software Foundation, Inc.
 *
 * This file was generated by gr_modtool, a tool from the GNU Radio framework
 * This file is a part of gr-robotics
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

#ifndef INCLUDED_ROBOTICS_API_H
#define INCLUDED_ROBOTICS_API_H

#include <gnuradio/attributes.h>

#ifdef gnuradio_robotics_EXPORTS
#define ROBOTICS_API __GR_ATTR_EXPORT
#else
#define ROBOTICS_API __GR_ATTR_IMPORT
#endif

#endif /* INCLUDED_ROBOTICS_API_H */
